BASE_URL: http://localhost:3000
FIREBASE_API_KEY: 'AIzaSyDVcTUePDsHKFCYwkwkGi6hxF638Ffkk8M'
FIREBASE_AUTH_DOMAIN: 'dev-shinya.firebaseapp.com'
FIREBASE_DATABASE_URL: 'https://dev-shinya.firebaseio.com'
FIREBASE_PROJECT_ID: 'dev-shinya'
FIREBASE_STORAGE_BUCKET: 'dev-shinya.appspot.com'
FIREBASE_MESSAGING_SENDER_ID: '241829961995'
FIREBASE_APP_ID: '1:241829961995:web:f39a6a225c049405ffc20e'
MEASUREMENT_ID: 'G-G9MT9C86P7'
GCLOUD_PROJECT: 'dev-shinya'