runtime: nodejs10

instance_class: F1


# runtime: nodejs10

# instance_class: F2


#   - url: /static
#     static_dir: static
#     secure: always

#   - url: /.*
#     secure: always
#     script: auto
