name:
  scraping-functions

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare Node Envinronment
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-version }}

      - name: Install expect command
        run: sudo apt-get install expect

      - name: Install firebase-tools
        run: sudo npm install -g firebase-tools

      - name: Install eslint and yarn
        run: |
          npm install -g eslint
          npm install -g yarn

      - name: Install Dependencies
        working-directory: ./functions
        run: yarn

      - name: Add Priviledge for firebase-tools
        run: sudo chown -R $USER:$(id -gn $USER) /home/runner/.config

      # Deploy
      - name: Deploy Cloud functions
        working-firectory: ./functions
        run: |
        echo $GCP_KEY > gcp_key.json
        echo 'github-actions@dev-shinya.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file gcp_key.json
        gcloud app deploy app.yaml --project dev-shinya

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}


