name:
  scraping-functions

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prepare Node Envinronment
        uses: actions/setup-node@v1
        with:
          node-versions: ${{ matrix.node-version }}

      - name: Install expect command
        run: sudo apt-get install expect

      - name: Install firebase-tools
        run: sudo npm install -g firebase-tools

      - name: Install eslint and yarn
        run: |
          npm install -g eslint
          npm install -g yarn

      - name: Install Dependencies
        working-directory: ./functions
        run: yarn

      - name: Add Priviledge for firebase-tools
        run: sudo chown -R $USER:$(id -gn $USER) /home/runner/.config

      # Deploy
      - name: Deploy Cloud functions
        working-directory: ./functions
        run: |
          firebase deploy --only functions --interactive --token $FIREBASE_TOKEN --project $PROJECT_ID

        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GCP_KEY: ${{ secrets.GCP_KEY }}

      #  Artifact生成前にnode_modulesを削除
      - name: Remove node_modules from artifact
        if: ${{ failure() }}
        run: rm -rf ./functions/node_module

      #  Artifact生成
      - name: Generate artifact file
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          path: './functions'
          name: functions.zip

          # gcloud auth activate-service-account \
          # dev-shinya@appspot.gserviceaccount.com \
          #   --key-file=$GCP_KEY --project=dev-shinya
          # gcloud app deploy app.yaml